In [14]:
import pandas as pd
import numpy as np

*Data Ingestion*

In [15]:
df=pd.read_csv("data.csv")

In [16]:
df.head()

      name                email  age
0    Alice    ALICE@example.com   25
1      Bob                  NaN   30
2  Charlie  charlie@example.com   17
3    David    david@example.com   40
4      Eve      eve@example.com   22

*Data Validation*

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   email   7 non-null      str
 2   age     8 non-null      int64
dtypes: int64(1), str(2)
memory usage: 324.0 bytes

In [18]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [19]:
df.describe()

             age
count   8.000000
mean   26.625000
std     7.909082
min    17.000000
25%    21.250000
50%    25.000000
75%    31.250000
max    40.000000

*Data Cleaning*

In [27]:
df.drop_duplicates(inplace=True)

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.isnull().sum()

name     0
email    0
age      0
dtype: int64

In [30]:
df.dropna(inplace=True)

In [31]:
df.isnull().sum()

name     0
email    0
age      0
dtype: int64

In [32]:
df.head()

      name                email  age
0    Alice    ALICE@example.com   25
2  Charlie  charlie@example.com   17
3    David    david@example.com   40
4      Eve      eve@example.com   22
6    Frank    frank@example.com   19

*Data Validation*

In [34]:
## validating email
import re
def val_email(email):
    pattern=r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    if re.match(pattern,email):
        return True
    else:
        return False
df['email_valid']=df['email'].apply(val_email)

In [36]:
df['email_valid'].value_counts()

email_valid
True    6
Name: count, dtype: int64

In [39]:
# Validating age
import re
def val_age(age):
    if  0<=int(age)<=100:
        return True
    else:
        return False
df['age_valid']=df['age'].apply(val_age)

In [40]:
df["age_valid"].value_counts()

age_valid
True    6
Name: count, dtype: int64

*Data Transformation*

In [41]:
## converting name in to lower case
df['name']=df["name"].str.lower()

In [42]:
df.head()

      name                email  age  email_valid  age_valid
0    alice    ALICE@example.com   25         True       True
2  charlie  charlie@example.com   17         True       True
3    david    david@example.com   40         True       True
4      eve      eve@example.com   22         True       True
6    frank    frank@example.com   19         True       True

*Data Storage*

In [44]:
df.to_csv("data_pipeline.csv",index=False)