In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv("/workspaces/Aress_Task/data/preprocessed_housing_data.csv")

In [3]:
df.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,16.403275,8.912069,1.609438,1.098612,1.386294,1.098612,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,16.321037,9.100637,1.609438,1.609438,1.609438,1.386294,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,16.321037,9.206433,1.386294,1.098612,1.098612,1.098612,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
3,16.318175,8.922792,1.609438,1.098612,1.098612,1.386294,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
4,16.250001,8.912069,1.609438,0.693147,1.098612,1.098612,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0

In [4]:
df.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,16.403275,8.912069,1.609438,1.098612,1.386294,1.098612,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,16.321037,9.100637,1.609438,1.609438,1.609438,1.386294,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,16.321037,9.206433,1.386294,1.098612,1.098612,1.098612,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
3,16.318175,8.922792,1.609438,1.098612,1.098612,1.386294,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
4,16.250001,8.912069,1.609438,0.693147,1.098612,1.098612,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [6]:
X=df.drop(['price'],axis=1)
y=df['price']

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

**linear Regression**

In [9]:
linear_model=LinearRegression()
linear_model.fit(X_train,y_train)
y_pred=linear_model.predict(X_test)

In [10]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mean_absolute_error(y_test,y_pred)
mean_squared_error(y_test,y_pred)
r2_score(y_test,y_pred)

0.6820442293705083

In [11]:
print(f"\n MAE: {mean_absolute_error(y_test,y_pred)}\n RMSE: {np.sqrt(mean_squared_error(y_test,y_pred))}\n R2score: {r2_score(y_test,y_pred)} \n MSE:{mean_squared_error(y_test,y_pred)}")

 MAE: 0.1977094330215978
 RMSE: 0.24777741555429675
 R2score: 0.6820442293705083
 MSE:0.061393647658766655

**Decision Tree Regressor**

In [12]:
from sklearn.tree import  DecisionTreeRegressor

In [13]:
decision_model= DecisionTreeRegressor()
decision_model.fit(X_train,y_train)
y_pred=decision_model.predict(X_test)

In [14]:
print(f"\n MAE: {mean_absolute_error(y_test,y_pred)}\n RMSE: {np.sqrt(mean_squared_error(y_test,y_pred))}\n R2score: {r2_score(y_test,y_pred)} \n MSE:{mean_squared_error(y_test,y_pred)}")

 MAE: 0.24282349905655362
 RMSE: 0.3127941369879536
 R2score: 0.49328882521678585
 MSE:0.09784017213403867

**Random Forest**

In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
Random_model=RandomForestRegressor()
Random_model.fit(X_train,y_train)
y_pred=Random_model.predict(X_test)

In [17]:
print(f"\n MAE: {mean_absolute_error(y_test,y_pred)}\n RMSE: {np.sqrt(mean_squared_error(y_test,y_pred))}\n R2score: {r2_score(y_test,y_pred)} \n MSE:{mean_squared_error(y_test,y_pred)}")

 MAE: 0.20707908883951265
 RMSE: 0.26571646229055274
 R2score: 0.6343376909420355
 MSE:0.07060523833220672